version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - app_network
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    networks:
      - app_network

    redis:
      image: redis:7.2-alpine
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - app_network

      postgres:
        image: postgres:15-alpine
        container_name: postgres_db
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: feature_flags
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: